application:
  environment: local
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${spring.flyway.url}
    username: ${spring.flyway.user}
    password: ${spring.flyway.password}
  flyway:
    baseline-on-migrate: true
    locations: classpath:database/migration
    out-of-order: false
    url: jdbc:postgresql://localhost:5432/portfoliodb
    user: portfoliotool
    password: teushka
    validate-on-migrate: true
logging:
  level:
    org.springframework.web: DEBUG