spring:
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: false
  profiles:
    active: local
crypto:
  path: "https://api.coingecko.com/api/v3/simple/price"
  supported: "https://api.coingecko.com/api/v3/coins/list"
  market-clean-rate: 60000