application:
  environment: unittest
jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: false
crypto:
  path: "https://localhost:8081/test"
  supported: "https://localhost:8081/supportedtest"
  market-clean-rate: 60000